// JSP Page automatically generated by Desiderata Software JSP generator
// Thu Nov 29 09:00:10 EST 2018

import javax.servlet.*;
import java.io.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.*;
import java.util.*;
import Com.Patel.*;;

public class desisoft_jsp_PreDeposit_jsp1543500010258 extends desisoft.server.JspBaseClass {

    int _ds_jsp_lnum = -1;
    public void _jspService( HttpServletRequest request, HttpServletResponse response )
                             throws ServletException, IOException
    {
        JspFactory factory = JspFactory.getDefaultFactory();
        PageContext pageContext = factory.getPageContext( this, request, response,
                                    null,
                                    true,
                                    JspWriter.DEFAULT_BUFFER,
                                    true
                                    );

        // implicit variables.
        HttpSession session = pageContext.getSession();
        JspWriter out = pageContext.getOut();
        ServletConfig config = getServletConfig();
        ServletContext application = config.getServletContext();
        Object page = this;
        try {
_ds_jsp_lnum = 1;
            out.println( "<!--" );
_ds_jsp_lnum = 2;
            out.println( "/******************************************************************************" );
_ds_jsp_lnum = 3;
            out.println( "*\tProgram Author: Dhara Patel for CSCI 6810 Java and the Internet       *" );
_ds_jsp_lnum = 4;
            out.println( "*\tDate: November,2018                                                   *" );
_ds_jsp_lnum = 5;
            out.println( "*******************************************************************************/" );
_ds_jsp_lnum = 6;
            out.println( "-->" );
_ds_jsp_lnum = 7;
            out.println();
_ds_jsp_lnum = 8;
            out.println();
_ds_jsp_lnum = 9;
            out.println();
_ds_jsp_lnum = 10;
            out.println();
_ds_jsp_lnum = 11;
            out.println();
_ds_jsp_lnum = 12;
            //***** Start Scriptlet, line 12
            
String sav[] = LoginServlet.getSavingAccountNumbers(request.getParameter("UserID"));
String check[] = LoginServlet.getCheckingAccountNumbers(request.getParameter("UserID"));

            //***** End Scriptlet, line 12
_ds_jsp_lnum = 15;
            out.println();
_ds_jsp_lnum = 16;
            out.println( "<HTML><HEAD></HEAD>" );
_ds_jsp_lnum = 17;
            out.println( "<Body background=\"Deposit.jpg\">" );
_ds_jsp_lnum = 18;
            out.println( "    <FORM NAME=\"DepositForm\" ACTION=\"/Deposit\" METHOD =\"POST\">" );
_ds_jsp_lnum = 19;
            out.print( "        <INPUT TYPE=\'hidden\' NAME=\'UserID\' VALUE=\'" );
            out.print( request.getParameter("UserID") );
            out.println( "\'>" );
_ds_jsp_lnum = 20;
            out.println( "         <br>" );
_ds_jsp_lnum = 21;
            out.println( "\t <br>" );
_ds_jsp_lnum = 22;
            out.println( "        <br>" );
_ds_jsp_lnum = 23;
            out.println( "        <center>" );
_ds_jsp_lnum = 24;
            out.println( "        <fieldset style=\"width:450px\">" );
_ds_jsp_lnum = 25;
            out.println( "         <legend align=\"left\"><b><font size =\'6\'color=\"red\">Deposit</font></b></legend><br>" );
_ds_jsp_lnum = 26;
            out.println( "        <TABLE cellPadding=3 ALIGN=\'center\'>" );
_ds_jsp_lnum = 27;
            out.println();
_ds_jsp_lnum = 28;
            out.println( "            <TR background=\'Deposit.jpg\'>" );
_ds_jsp_lnum = 29;
            out.println( "                <TD><B><font size =\'5\'>Deposit To:</font></B></TD>" );
_ds_jsp_lnum = 30;
            out.println( "                <TD>" );
_ds_jsp_lnum = 31;
            out.println( "\t\t\t<select size=\"1\" name=\"CheckingOrSavings\">" );
_ds_jsp_lnum = 32;
            out.println( "\t\t\t\t<option selected value=\"x\">Checking Account</option>" );
_ds_jsp_lnum = 33;
            out.print( "\t\t\t\t" );
            //***** Start Scriptlet, line 33
             for(int i = 0; i < check.length; i++) {
				if(check[i] != null) {
					out.println("<option value='c" + check[i] + "'>Checking- ****"+ check[i].substring(4) + "</option>");
				}
				}
            //***** End Scriptlet, line 33
_ds_jsp_lnum = 37;
            out.println();
_ds_jsp_lnum = 38;
            out.println( "\t\t\t\t<option value=\"x\"><b></u>Savings Account<u></b></option> " );
_ds_jsp_lnum = 39;
            out.print( "\t\t\t\t" );
            //***** Start Scriptlet, line 39
             for(int i = 0; i < sav.length; i++) {
				if(sav[i] != null) {
					out.println("<option value='s" + sav[i] + "'>Savings- ****"+ sav[i].substring(4) + "</option>");
				}
				}
            //***** End Scriptlet, line 39
_ds_jsp_lnum = 43;
            out.println( "\t" );
_ds_jsp_lnum = 44;
            out.println( "\t\t\t</select>" );
_ds_jsp_lnum = 45;
            out.println( "                </TD>" );
_ds_jsp_lnum = 46;
            out.println( "            </TR>" );
_ds_jsp_lnum = 47;
            out.println();
_ds_jsp_lnum = 48;
            out.println( "            <TR background=\'Deposite.jpg\'>" );
_ds_jsp_lnum = 49;
            out.println( "                <TD><B><font size =\'5\'>Amount to Deposit:</font></B></TD>" );
_ds_jsp_lnum = 50;
            out.println( "                <TD>" );
_ds_jsp_lnum = 51;
            out.println( "                   <INPUT TYPE=\'text\' NAME=\'AmountField\' Value=\'\' SIZE=\'15\' placeholder=\'Enter Amount\'>" );
_ds_jsp_lnum = 52;
            out.println( "                </TD>" );
_ds_jsp_lnum = 53;
            out.println( "            </TR>" );
_ds_jsp_lnum = 54;
            out.println( "          </TABLE><BR>" );
_ds_jsp_lnum = 55;
            out.println( "<CENTER><INPUT TYPE=\"SUBMIT\" NAME=\'submitBNTN\' VALUE=\'Make Deposit\' style=\"font-size:12pt;color:white;background-color:black;border:2px solid #336600;padding:7px\"></CENTER><BR>" );
_ds_jsp_lnum = 56;
            out.println( "</fieldset>" );
_ds_jsp_lnum = 57;
            out.println( "</center>" );
_ds_jsp_lnum = 58;
            out.println( "</FORM>" );
_ds_jsp_lnum = 59;
            out.println();
_ds_jsp_lnum = 60;
            out.println( "</BODY>" );
_ds_jsp_lnum = 61;
            out.println( "</HTML>" );
_ds_jsp_lnum = 62;
            out.println( "<SCRIPT LANGUAGE=\'JavaScript\'>" );
_ds_jsp_lnum = 63;
            out.print( "</SCRIPT>" );
        } catch (Exception ex) {
            out.clearBuffer();
            request.setAttribute( "javax.servlet.jsp.jspException", ex );
            request.setAttribute( "desisoft.jsp.lineNumber", new Integer( _ds_jsp_lnum ));
            pageContext.handlePageException(ex);
        } finally {
            factory.releasePageContext(pageContext);
        }
    }


    public String[] _desisoft_jsp_getDependentFiles() { return _desisoft_jsp_dependencyList; }
    public long[] _desisoft_jsp_getModTimes() { return _desisoft_jsp_dependencyModTimes; }

    static String[] _desisoft_jsp_dependencyList = { "PreDeposit.jsp" };
    static long [] _desisoft_jsp_dependencyModTimes = { 1543499965200L };

}
