// JSP Page automatically generated by Desiderata Software JSP generator
// Thu Nov 29 09:00:07 EST 2018

import javax.servlet.*;
import java.io.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.*;
import java.util.*;
import Com.Patel.*;;

public class desisoft_jsp_PreTransfer_jsp1543500007158 extends desisoft.server.JspBaseClass {

    int _ds_jsp_lnum = -1;
    public void _jspService( HttpServletRequest request, HttpServletResponse response )
                             throws ServletException, IOException
    {
        JspFactory factory = JspFactory.getDefaultFactory();
        PageContext pageContext = factory.getPageContext( this, request, response,
                                    null,
                                    true,
                                    JspWriter.DEFAULT_BUFFER,
                                    true
                                    );

        // implicit variables.
        HttpSession session = pageContext.getSession();
        JspWriter out = pageContext.getOut();
        ServletConfig config = getServletConfig();
        ServletContext application = config.getServletContext();
        Object page = this;
        try {
_ds_jsp_lnum = 1;
            out.println( "<!--" );
_ds_jsp_lnum = 2;
            out.println( "/******************************************************************************" );
_ds_jsp_lnum = 3;
            out.println( "*\tProgram Author: Dhara Patel for CSCI 6810 Java and the Internet       *" );
_ds_jsp_lnum = 4;
            out.println( "*\tDate: November,2018                                                   *" );
_ds_jsp_lnum = 5;
            out.println( "*******************************************************************************/" );
_ds_jsp_lnum = 6;
            out.println( "-->" );
_ds_jsp_lnum = 7;
            out.println();
_ds_jsp_lnum = 8;
            out.println();
_ds_jsp_lnum = 9;
            out.println();
_ds_jsp_lnum = 10;
            out.println();
_ds_jsp_lnum = 11;
            out.println();
_ds_jsp_lnum = 12;
            //***** Start Scriptlet, line 12
            
String sav[] = LoginServlet.getSavingAccountNumbers(request.getParameter("UserID"));
String check[] = LoginServlet.getCheckingAccountNumbers(request.getParameter("UserID"));

            //***** End Scriptlet, line 12
_ds_jsp_lnum = 15;
            out.println();
_ds_jsp_lnum = 16;
            out.println();
_ds_jsp_lnum = 17;
            out.println( "<HTML><HEAD></HEAD>" );
_ds_jsp_lnum = 18;
            out.println( "<Body background=\"Transfer.jpg\">" );
_ds_jsp_lnum = 19;
            out.println( "    <FORM NAME=\"TransferForm\" ACTION=\"/Transfer\" METHOD =\"POST\">" );
_ds_jsp_lnum = 20;
            out.print( "        <INPUT TYPE=\'hidden\' NAME=\'UserID\' VALUE=\'" );
            out.print( request.getParameter("UserID") );
            out.println( "\'>" );
_ds_jsp_lnum = 21;
            out.println( "\t<br>" );
_ds_jsp_lnum = 22;
            out.println( "\t<br>" );
_ds_jsp_lnum = 23;
            out.println( "\t<br>" );
_ds_jsp_lnum = 24;
            out.println( "\t<center>" );
_ds_jsp_lnum = 25;
            out.println( "\t<fieldset style=\"width:450px\">" );
_ds_jsp_lnum = 26;
            out.println( "         <legend align=\"left\"><b><font size =\'6\'color=\"red\">Transfer</font></b></legend><br>" );
_ds_jsp_lnum = 27;
            out.println( "        <TABLE cellPadding=3 ALIGN=\'center\'>" );
_ds_jsp_lnum = 28;
            out.println();
_ds_jsp_lnum = 29;
            out.println( "            <TR background=\'Transfer.jpg\'>" );
_ds_jsp_lnum = 30;
            out.println( "                <TD><B><font size =\'5\'>Transfer From:</font></B></TD>" );
_ds_jsp_lnum = 31;
            out.println( "                <TD>" );
_ds_jsp_lnum = 32;
            out.println( "\t\t    <select size=\"1\" name=\"FromAccount\">" );
_ds_jsp_lnum = 33;
            out.println( "\t\t\t<option selected value=\"x\"><b><u>Checking Account</u></b></option>" );
_ds_jsp_lnum = 34;
            out.print( "\t\t\t" );
            //***** Start Scriptlet, line 34
             for(int i = 0; i < check.length; i++) {
			if(check[i] != null) {
				out.println("<option value='c" + check[i] + "'>Checking- ****"+ check[i].substring(4) + "</option>"); 
			}
			}
			
            //***** End Scriptlet, line 34
_ds_jsp_lnum = 39;
            out.println();
_ds_jsp_lnum = 40;
            out.println( "\t\t\t<option value=\"x\"><b><u>Savings Account</u></b></option> " );
_ds_jsp_lnum = 41;
            out.print( "\t\t\t" );
            //***** Start Scriptlet, line 41
             for(int i = 0; i < sav.length; i++) {
			if(sav[i] != null) {
				out.println("<option value='s" + sav[i] + "'>Savings- ****"+ sav[i].substring(4) + "</option>"); 
			}
			}
			
            //***** End Scriptlet, line 41
_ds_jsp_lnum = 46;
            out.println();
_ds_jsp_lnum = 47;
            out.println( "\t\t    </select>" );
_ds_jsp_lnum = 48;
            out.println( "                </TD>" );
_ds_jsp_lnum = 49;
            out.println( "            </TR>" );
_ds_jsp_lnum = 50;
            out.println( "            <TR background=\'Transfer.jpg\'>" );
_ds_jsp_lnum = 51;
            out.println( "                <TD><B><font size =\'5\'>Transfer To:</font></B></TD>" );
_ds_jsp_lnum = 52;
            out.println( "                <TD>" );
_ds_jsp_lnum = 53;
            out.println( "\t\t    <select size=\"1\" name=\"ToAccount\">" );
_ds_jsp_lnum = 54;
            out.println( "\t\t\t<option selected value=\"x\"><b><u>Checking Account</u></b></option>" );
_ds_jsp_lnum = 55;
            out.print( "\t\t\t" );
            //***** Start Scriptlet, line 55
             for(int i = 0; i < check.length; i++) {
			if(check[i] != null) {
				out.println("<option value='c" + check[i] + "'>Checking- ****"+ check[i].substring(4) + "</option>"); 
			}
			}
			
            //***** End Scriptlet, line 55
_ds_jsp_lnum = 60;
            out.println();
_ds_jsp_lnum = 61;
            out.println( "\t\t\t<option value=\"x\"><b><u>Savings Account</u></b></option> " );
_ds_jsp_lnum = 62;
            out.print( "\t\t\t" );
            //***** Start Scriptlet, line 62
             for(int i = 0; i < sav.length; i++) {
			if(sav[i] != null) {
				out.println("<option value='s" + sav[i] + "'>Savings- ****"+ sav[i].substring(4) + "</option>"); 
			}
			}
			
            //***** End Scriptlet, line 62
_ds_jsp_lnum = 67;
            out.println();
_ds_jsp_lnum = 68;
            out.println( "\t\t    </select>" );
_ds_jsp_lnum = 69;
            out.println( "                </TD>" );
_ds_jsp_lnum = 70;
            out.println( "            </TR>" );
_ds_jsp_lnum = 71;
            out.println( "            <TR background=\'Transfer.jpg\'>" );
_ds_jsp_lnum = 72;
            out.println( "                <TD><B><font size =\'5\'>Amount to Transfer:</font</B></TD>" );
_ds_jsp_lnum = 73;
            out.println( "                <TD>" );
_ds_jsp_lnum = 74;
            out.println( "                   <INPUT TYPE=\'text\' NAME=\'AmountField\' Value=\'\' SIZE=\'15\' placeholder=\'Enter Amount\'>" );
_ds_jsp_lnum = 75;
            out.println( "                </TD>" );
_ds_jsp_lnum = 76;
            out.println( "            </TR>" );
_ds_jsp_lnum = 77;
            out.println( "          </TABLE><BR>" );
_ds_jsp_lnum = 78;
            out.println( "<CENTER><INPUT TYPE=\"SUBMIT\" NAME=\'submitBNTN\' VALUE=\'Make Transfer\' style=\"font-size:12pt;color:white;background-color:black;border:2px solid #336600;padding:7px\"></CENTER><BR>" );
_ds_jsp_lnum = 79;
            out.println( "</fieldset>" );
_ds_jsp_lnum = 80;
            out.println( "</center>" );
_ds_jsp_lnum = 81;
            out.println( "</FORM>" );
_ds_jsp_lnum = 82;
            out.println( "</BODY>" );
_ds_jsp_lnum = 83;
            out.println( "</HTML>" );
_ds_jsp_lnum = 84;
            out.println( "<SCRIPT LANGUAGE=\'JavaScript\'>" );
_ds_jsp_lnum = 85;
            out.print( "</SCRIPT>" );
        } catch (Exception ex) {
            out.clearBuffer();
            request.setAttribute( "javax.servlet.jsp.jspException", ex );
            request.setAttribute( "desisoft.jsp.lineNumber", new Integer( _ds_jsp_lnum ));
            pageContext.handlePageException(ex);
        } finally {
            factory.releasePageContext(pageContext);
        }
    }


    public String[] _desisoft_jsp_getDependentFiles() { return _desisoft_jsp_dependencyList; }
    public long[] _desisoft_jsp_getModTimes() { return _desisoft_jsp_dependencyModTimes; }

    static String[] _desisoft_jsp_dependencyList = { "PreTransfer.jsp" };
    static long [] _desisoft_jsp_dependencyModTimes = { 1543500004120L };

}
