// JSP Page automatically generated by Desiderata Software JSP generator
// Sat Nov 24 11:19:46 EST 2018

import javax.servlet.*;
import java.io.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.*;
import java.util.*;
import Com.Patel.*;;

public class desisoft_jsp_SignUp_jsp1543076386672 extends desisoft.server.JspBaseClass {

    int _ds_jsp_lnum = -1;
    public void _jspService( HttpServletRequest request, HttpServletResponse response )
                             throws ServletException, IOException
    {
        JspFactory factory = JspFactory.getDefaultFactory();
        PageContext pageContext = factory.getPageContext( this, request, response,
                                    null,
                                    true,
                                    JspWriter.DEFAULT_BUFFER,
                                    true
                                    );

        // implicit variables.
        HttpSession session = pageContext.getSession();
        JspWriter out = pageContext.getOut();
        ServletConfig config = getServletConfig();
        ServletContext application = config.getServletContext();
        Object page = this;
        try {
_ds_jsp_lnum = 1;
            out.println( "<!--" );
_ds_jsp_lnum = 2;
            out.println( "/******************************************************************************" );
_ds_jsp_lnum = 3;
            out.println( "*\tProgram Author: Dr. Yongming Tang for CSCI 6810 Java and the Internet *" );
_ds_jsp_lnum = 4;
            out.println( "*\tDate: September, 2012\t\t\t\t\t\t      *" );
_ds_jsp_lnum = 5;
            out.println( "*******************************************************************************/" );
_ds_jsp_lnum = 6;
            out.println( "-->" );
_ds_jsp_lnum = 7;
            out.println();
_ds_jsp_lnum = 8;
            out.println();
_ds_jsp_lnum = 9;
            out.println();
_ds_jsp_lnum = 10;
            out.println();
_ds_jsp_lnum = 11;
            out.println();
_ds_jsp_lnum = 12;
            out.println();
_ds_jsp_lnum = 13;
            //***** Start Scriptlet, line 13
            
	String Username = new String("");
	String Password = new String("");
	String Re_enterPassword = new String("");
	String FullName = new String("");
	
	Username = request.getParameter( "UsernameField" );
	Password = request.getParameter( "PasswordField" );
        Re_enterPassword = request.getParameter( "RePasswordField" );
        FullName = request.getParameter( "NameField" );
              
        Account Acct = new Account(Username, Password, Re_enterPassword, FullName);

	if (!Acct.signUp())
            out.println("Account creation failed because of existing username or invalid username. Please try again!");
        else { 

            //***** End Scriptlet, line 13
_ds_jsp_lnum = 29;
            out.println();
_ds_jsp_lnum = 30;
            out.println();
_ds_jsp_lnum = 31;
            out.println( "\t\t<HTML><HEAD></HEAD>" );
_ds_jsp_lnum = 32;
            out.println( "\t\t<Body background=\"3.jpg\">" );
_ds_jsp_lnum = 33;
            out.println( "\t\t<h4 ALIGN=\'center\'>Congratulations! You have an account with us. Thank you! You can login now.</h4>" );
_ds_jsp_lnum = 34;
            out.println( "\t\t<FORM NAME=\"LoginPage\" ACTION=\"/LoginSrvlet\" METHOD =\"POST\">" );
_ds_jsp_lnum = 35;
            out.println( "\t\t" );
_ds_jsp_lnum = 36;
            out.println( "\t\t<TABLE cellPadding=\'3\' ALIGN=\'center\'>" );
_ds_jsp_lnum = 37;
            out.println( "\t\t<TR bgcolor=\'#ECFAEB\'>" );
_ds_jsp_lnum = 38;
            out.println( "\t\t<TD><B>USERNAME:</B></TD>" );
_ds_jsp_lnum = 39;
            out.println( "\t\t<TD>" );
_ds_jsp_lnum = 40;
            out.print( "\t\t<INPUT TYPE=\'text\' NAME=\'UserName\' Value=\'" );
            out.print(  Username  );
            out.println( "\' SIZE=\'15\'  placeholder=\'Enter Username\' focused>" );
_ds_jsp_lnum = 41;
            out.println( "\t\t</TD>" );
_ds_jsp_lnum = 42;
            out.println( "\t\t</TR>" );
_ds_jsp_lnum = 43;
            out.println( "\t\t<TR bgcolor=\'#ECFAEB\'>" );
_ds_jsp_lnum = 44;
            out.println( "\t\t<TD><B>PASSWORD:</B></TD>" );
_ds_jsp_lnum = 45;
            out.println( "\t\t<TD>" );
_ds_jsp_lnum = 46;
            out.println( "\t\t<INPUT TYPE=\'password\' NAME=\'PassWord\' Value=\'\' SIZE=\'15\' placeholder=\'Enter Password\'>" );
_ds_jsp_lnum = 47;
            out.println( "\t\t<INPUT TYPE=\'button\' NAME=\'submitBTN\' VALUE=\'Login\' onClick=\"checkInputs()\" style=\"font-size:12pt;color:white;background-color:black;border:2px solid #336600;padding:7px\">" );
_ds_jsp_lnum = 48;
            out.println( "\t\t</TD>" );
_ds_jsp_lnum = 49;
            out.println( "\t\t</TR>" );
_ds_jsp_lnum = 50;
            out.println( "\t\t</TABLE>" );
_ds_jsp_lnum = 51;
            out.println( "\t\t</FORM>" );
_ds_jsp_lnum = 52;
            out.println( "\t\t</BODY>" );
_ds_jsp_lnum = 53;
            out.println( "\t\t<SCRIPT LANGUAGE=\"JavaScript\"> " );
_ds_jsp_lnum = 54;
            out.println( "\t\tfunction checkInputs()" );
_ds_jsp_lnum = 55;
            out.println( "\t\t{" );
_ds_jsp_lnum = 56;
            out.println( "\t\tvar Prompts = \"\";" );
_ds_jsp_lnum = 57;
            out.println( "\t\tUsername = window.document.LoginPage.UserName.value;" );
_ds_jsp_lnum = 58;
            out.println( "\t\tPassword = window.document.LoginPage.PassWord.value;" );
_ds_jsp_lnum = 59;
            out.println( "\t\tif (Username == \"\" || Password == \"\") {" );
_ds_jsp_lnum = 60;
            out.println( "\t\tif (Username == \"\")" );
_ds_jsp_lnum = 61;
            out.println( "\t\tPrompts +=\"Please enter your username!\\n\";" );
_ds_jsp_lnum = 62;
            out.println( "\t\tif (Password == \"\")" );
_ds_jsp_lnum = 63;
            out.println( "\t\tPrompts +=\"Please enter your password!\\n\";" );
_ds_jsp_lnum = 64;
            out.println( "\t\tif (Prompts != \"\")" );
_ds_jsp_lnum = 65;
            out.println( "\t\twindow.alert(Prompts);" );
_ds_jsp_lnum = 66;
            out.println( "\t\t} else {" );
_ds_jsp_lnum = 67;
            out.println( "\t\tdocument.LoginPage.submit();" );
_ds_jsp_lnum = 68;
            out.println( "\t\t}" );
_ds_jsp_lnum = 69;
            out.println( "\t\t}" );
_ds_jsp_lnum = 70;
            out.println( "\t\t</SCRIPT>" );
_ds_jsp_lnum = 71;
            out.println( "\t\t</HTML>" );
_ds_jsp_lnum = 72;
            out.println();
_ds_jsp_lnum = 73;
            //***** Start Scriptlet, line 73
            		}

            //***** End Scriptlet, line 73
_ds_jsp_lnum = 74;
            out.println();
_ds_jsp_lnum = 75;
            out.println( " " );
_ds_jsp_lnum = 76;
        } catch (Exception ex) {
            out.clearBuffer();
            request.setAttribute( "javax.servlet.jsp.jspException", ex );
            request.setAttribute( "desisoft.jsp.lineNumber", new Integer( _ds_jsp_lnum ));
            pageContext.handlePageException(ex);
        } finally {
            factory.releasePageContext(pageContext);
        }
    }


    public String[] _desisoft_jsp_getDependentFiles() { return _desisoft_jsp_dependencyList; }
    public long[] _desisoft_jsp_getModTimes() { return _desisoft_jsp_dependencyModTimes; }

    static String[] _desisoft_jsp_dependencyList = { "SignUp.jsp" };
    static long [] _desisoft_jsp_dependencyModTimes = { 1542482470093L };

}
