// JSP Page automatically generated by Desiderata Software JSP generator
// Thu Nov 22 23:58:11 EST 2018

import javax.servlet.*;
import java.io.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public class desisoft_jsp_Transfer_jsp1542949091441 extends desisoft.server.JspBaseClass {

    int _ds_jsp_lnum = -1;
    public void _jspService( HttpServletRequest request, HttpServletResponse response )
                             throws ServletException, IOException
    {
        JspFactory factory = JspFactory.getDefaultFactory();
        PageContext pageContext = factory.getPageContext( this, request, response,
                                    null,
                                    true,
                                    JspWriter.DEFAULT_BUFFER,
                                    true
                                    );

        // implicit variables.
        HttpSession session = pageContext.getSession();
        JspWriter out = pageContext.getOut();
        ServletConfig config = getServletConfig();
        ServletContext application = config.getServletContext();
        Object page = this;
        try {
_ds_jsp_lnum = 1;
            out.println( "<!--" );
_ds_jsp_lnum = 2;
            out.println( "/******************************************************************************" );
_ds_jsp_lnum = 3;
            out.println( "*\tProgram Author: Dhara Patel for CSCI 6810 Java and the Internet       *" );
_ds_jsp_lnum = 4;
            out.println( "*\tDate: November,2018                                                   *" );
_ds_jsp_lnum = 5;
            out.println( "*******************************************************************************/" );
_ds_jsp_lnum = 6;
            out.println( "-->" );
_ds_jsp_lnum = 7;
            out.println();
_ds_jsp_lnum = 8;
            out.println( "<HTML><HEAD></HEAD>" );
_ds_jsp_lnum = 9;
            out.println( "<Body background=\"3.jpg\">" );
_ds_jsp_lnum = 10;
            out.println( "    <FORM NAME=\"TransferForm\" ACTION=\"/Transfer\" METHOD =\"POST\">" );
_ds_jsp_lnum = 11;
            out.print( "        <INPUT TYPE=\'hidden\' NAME=\'UserID\' VALUE=\'" );
            out.print( request.getParameter("UserID") );
            out.println( "\'>" );
_ds_jsp_lnum = 12;
            out.println( "\t<h2><center><I><font color=\"Blue\">Transfer Form</font></I></center><h2>" );
_ds_jsp_lnum = 13;
            out.println( "        <TABLE cellPadding=3 ALIGN=\'center\'>" );
_ds_jsp_lnum = 14;
            out.println();
_ds_jsp_lnum = 15;
            out.println( "            <TR bgcolor=\'#ECFAEB\'>" );
_ds_jsp_lnum = 16;
            out.println( "                <TD><B>Transfer From:</B></TD>" );
_ds_jsp_lnum = 17;
            out.println( "                <TD>" );
_ds_jsp_lnum = 18;
            out.println( "                    <select size=\"1\" name=\"FromCheckingOrSavings\">" );
_ds_jsp_lnum = 19;
            out.println( "\t\t    \t<option selected value=\"Checking\">Checking</option>" );
_ds_jsp_lnum = 20;
            out.println( "\t\t    \t<option value=\"Savings\">Savings</option>" );
_ds_jsp_lnum = 21;
            out.println( "  \t            </select>" );
_ds_jsp_lnum = 22;
            out.println( "                </TD>" );
_ds_jsp_lnum = 23;
            out.println( "            </TR>" );
_ds_jsp_lnum = 24;
            out.println( "            <TR bgcolor=\'#F1F1FD\'>" );
_ds_jsp_lnum = 25;
            out.println( "                <TD><B>Transfer To:</B></TD>" );
_ds_jsp_lnum = 26;
            out.println( "                <TD>" );
_ds_jsp_lnum = 27;
            out.println( "                    <select size=\"1\" name=\"ToCheckingOrSavings\">" );
_ds_jsp_lnum = 28;
            out.println( "\t\t    \t<option value=\"Checking\">Checking</option>" );
_ds_jsp_lnum = 29;
            out.println( "\t\t    \t<option selected value=\"Savings\">Savings</option>" );
_ds_jsp_lnum = 30;
            out.println( "  \t            </select>" );
_ds_jsp_lnum = 31;
            out.println( "                </TD>" );
_ds_jsp_lnum = 32;
            out.println( "            </TR>" );
_ds_jsp_lnum = 33;
            out.println( "            <TR bgcolor=\'#ECFAEB\'>" );
_ds_jsp_lnum = 34;
            out.println( "                <TD><B>Amount to Transfer:</B></TD>" );
_ds_jsp_lnum = 35;
            out.println( "                <TD>" );
_ds_jsp_lnum = 36;
            out.println( "                   <INPUT TYPE=\'text\' NAME=\'AmountField\' Value=\'\' SIZE=\'15\' placeholder=\'Enter Amount\'>" );
_ds_jsp_lnum = 37;
            out.println( "                </TD>" );
_ds_jsp_lnum = 38;
            out.println( "            </TR>" );
_ds_jsp_lnum = 39;
            out.println( "          </TABLE><BR>" );
_ds_jsp_lnum = 40;
            out.println( "<CENTER><INPUT TYPE=\"SUBMIT\" NAME=\'submitBNTN\' VALUE=\'Make Transfer\' style=\"font-size:12pt;color:white;background-color:black;border:2px solid #336600;padding:7px\"></CENTER><BR>" );
_ds_jsp_lnum = 41;
            out.println( "</FORM>" );
_ds_jsp_lnum = 42;
            out.println();
_ds_jsp_lnum = 43;
            out.println( "</BODY>" );
_ds_jsp_lnum = 44;
            out.println( "</HTML>" );
_ds_jsp_lnum = 45;
            out.println( "<SCRIPT LANGUAGE=\'JavaScript\'>" );
_ds_jsp_lnum = 46;
            out.print( "</SCRIPT>" );
        } catch (Exception ex) {
            out.clearBuffer();
            request.setAttribute( "javax.servlet.jsp.jspException", ex );
            request.setAttribute( "desisoft.jsp.lineNumber", new Integer( _ds_jsp_lnum ));
            pageContext.handlePageException(ex);
        } finally {
            factory.releasePageContext(pageContext);
        }
    }


    public String[] _desisoft_jsp_getDependentFiles() { return _desisoft_jsp_dependencyList; }
    public long[] _desisoft_jsp_getModTimes() { return _desisoft_jsp_dependencyModTimes; }

    static String[] _desisoft_jsp_dependencyList = { "Transfer.jsp" };
    static long [] _desisoft_jsp_dependencyModTimes = { 1542949080269L };

}
